language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "nightly"
install: pip install pytest pytest-cov python-coveralls
script: py.test --cov diaper test_diaper.py
after_success:
  - coveralls
